spring:
  application:
    name: eureka-server-ha
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456