server:
  port: 8282
spring:
  application:
    name: microservice-provider-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8762/eureka/
  instance:
    prefer-ip-address: true