
drop table user if exists;
CREATE TABLE user(
  id bigint generated BY DEFAULT AS IDENTITY,
  username VARCHAR(40),
   name VARCHAR(20),
   age int(3),
   balance DECIMAL(10, 2),
   PRIMARY KEY (id)
);
