server:
  port: 8283
spring:
  application:
    name: microservice-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/, http://user:123456@localhost:8762/eureka/
  instance:
    prefer-ip-address: true
