server:
  port: 8283
spring:
  application:
    name: microservice-consumer-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
